version: "3.7"

services:

  msprodutos:
    container_name: msprodutos
    build:
      context: /msproduto
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbproduto:3306/produtos?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - dbproduto
    networks:
      - minha-rede

  dbproduto:
    container_name: dbproduto
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: produtos
    volumes:
      - db_produto:/var/lib/mysql
    networks:
      - minha-rede

  dbcliente:
    container_name: dbcliente
    image: mysql:5.7
    ports:
      - '3305:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clientes
    volumes:
      - db_client:/var/lib/mysql
    networks:
      - minha-rede

  dbpagamento:
    container_name: dbpagamento
    image: mysql:5.7
    ports:
      - '3311:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pagamentos
    volumes:
      - db_pagament:/var/lib/mysql
    networks:
      - minha-rede


  dbcarrinhocompras:
    container_name: dbcarrinhocompras
    image: mysql:5.7
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: carrinhocompras
    volumes:
      - db_carrinhocompras:/var/lib/mysql
    networks:
      - minha-rede

  mscarrinhocompras:
    container_name: mscarrinhocompras
    build:
      context: /mscarrinhocompras
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbcarrinhocompras:3306/carrinhocompras?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - dbcarrinhocompras
    networks:
      - minha-rede

  msclientes:
    container_name: msclientes
    build:
      context: /mscliente
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbcliente:3306/clientes?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - dbcliente
    networks:
      - minha-rede

  mspagamento:
    container_name: mspagamentos
    build:
      context: /mspagamento
      dockerfile: Dockerfile
    ports:
      - '8089:8089'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbpagamento:3306/pagamentos?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - dbpagamento
    networks:
      - minha-rede


  mslogin:
    container_name: mslogin
    build:
      context: /mslogin
      dockerfile: Dockerfile
    ports:
      - '8099:8099'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbusuario:3306/usuarios?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - dbusuario
    networks:
      - minha-rede

  dbusuario:
    container_name: dbusuario
    image: mysql:5.7
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usuarios
    volumes:
      - db_usuario:/var/lib/mysql
    networks:
      - minha-rede


networks:
  minha-rede:
    driver: bridge

volumes:
  db_client:
  db_pagament:
  db_usuario:
  db_produto:
  db_carrinhocompras:
