version: "3.7"

services:

  dbcliente:
    container_name: dbcliente
    image: mysql:5.7
    ports:
      - '3305:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clientes
    volumes:
      - db_client:/var/lib/mysql
    networks:
      - minha-rede

  msclientes:
    container_name: msclientes
    build:
      context: /mscliente
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbcliente:3306/clientes?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - dbcliente
    networks:
      - minha-rede

  mslogin:
    container_name: mslogin
    build:
      context: /mslogin
      dockerfile: Dockerfile
    ports:
      - '8099:8099'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbusuario:3306/usuarios?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - dbusuario
    networks:
      - minha-rede

  dbusuario:
    container_name: dbusuario
    image: mysql:5.7
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usuarios
    volumes:
      - db_usuario:/var/lib/mysql
    networks:
      - minha-rede


networks:
  minha-rede:
    driver: bridge

volumes:
  db_client:
  db_usuario:
