server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://dbpagamento:3306/pagamentos?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
api:
  security:
    token:
      secret=${JWT_SECRET:66e48fcca777ed0975ff8a7f51198db678aea9661298bcd34adace1ecefa2cce}: